### ISSUE TITLE
部署完成，进入订阅地址后报错

### ISSUE THREAD

**Issue by jayling1111** [SubConv/SubConv#1]
This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

<img width="762" alt="截屏2023-12-14 01 33 26" src="https://github.com/SubConv/SubConv/assets/84979549/fb0f2b92-b16a-41df-9bfa-ff912bc71092">

**Comment by wouiSB** [comment]
You should manually run the action to make cache for the first time

**Comment by jayling1111** [comment]
> You should manually run the action to make cache for the first time

i have action,not work still

**Comment by jayling1111** [comment]
[ERROR] Exception: No valid proxies found
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 305, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 208, in __call__
    loop.run_until_complete(asgi_task)
  File "/var/lang/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/task/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/var/task/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/task/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/var/task/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/var/task/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/var/task/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/var/task/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/var/task/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/var/task/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/var/task/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/var/task/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "./api.py", line 101, in sub
    urlstandalone = await converter.ConvertsV2Ray(urlstandalone)
  File "/var/task/modules/convert/converter.py", line 521, in ConvertsV2Ray
    raise Exception("No valid proxies found")

**Comment by wouiSB** [comment]
I've not fully tested hysteria and TUIC cuz I don't have a corresponding subscription. Can you send me your subscription url to <wouisb@is-sb.com> only for debug usage. It's also okey to send me the content of the subscription with all password fields (and other sensitive fields) replaced

**Comment by wouiSB** [comment]
A fix has been commited. You may update your fork and have a try

**Comment by wouiSB** [comment]
> [ERROR] Exception: No valid proxies found Traceback (most recent call last):   File "/var/task/vc__handler__python.py", line 305, in vc_handler     response = asgi_cycle(__vc_module.app, body)   File "/var/task/vc__handler__python.py", line 208, in **call**     loop.run_until_complete(asgi_task)   File "/var/lang/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete     return future.result()   File "/var/task/fastapi/applications.py", line 1106, in **call**     await super().**call**(scope, receive, send)   File "/var/task/starlette/applications.py", line 122, in **call**     await self.middleware_stack(scope, receive, send)   File "/var/task/starlette/middleware/errors.py", line 184, in **call**     raise exc   File "/var/task/starlette/middleware/errors.py", line 162, in **call**     await self.app(scope, receive, _send)   File "/var/task/starlette/middleware/exceptions.py", line 79, in **call**     raise exc   File "/var/task/starlette/middleware/exceptions.py", line 68, in **call**     await self.app(scope, receive, sender)   File "/var/task/fastapi/middleware/asyncexitstack.py", line 20, in **call**     raise e   File "/var/task/fastapi/middleware/asyncexitstack.py", line 17, in **call**     await self.app(scope, receive, send)   File "/var/task/starlette/routing.py", line 718, in **call**     await route.handle(scope, receive, send)   File "/var/task/starlette/routing.py", line 276, in handle     await self.app(scope, receive, send)   File "/var/task/starlette/routing.py", line 66, in app     response = await func(request)   File "/var/task/fastapi/routing.py", line 274, in app     raw_response = await run_endpoint_function(   File "/var/task/fastapi/routing.py", line 191, in run_endpoint_function     return await dependant.call(**values)   File "./api.py", line 101, in sub     urlstandalone = await converter.ConvertsV2Ray(urlstandalone)   File "/var/task/modules/convert/converter.py", line 521, in ConvertsV2Ray     raise Exception("No valid proxies found")

By the way, in my test I didn't meet this problem. But I did found other problems and tried to fix them.
I've tested a hy2 airport and it it works

**Comment by jayling1111** [comment]
好了，转换成功，谢谢
