### ISSUE TITLE
如何替换为自己的config模板

### ISSUE THREAD

**Issue by jayling1111** [SubConv/SubConv#2]
如果我仅需要转换节点信息，不使用你仓库的内置的模板，我该如何修改生成后的订阅连接？
像acl那边的话我可以通过在订阅连接后面添加&config=仓库地址 这种方式实现。

**Comment by wouiSB** [comment]
You can refer to [docs](https://subconv.is-sb.com/zh_CN/guide/introduction/what-is-subconv.html) for customization.

**Comment by wouiSB** [comment]
By the way, using `config=` to specify remote config files will cause potential safety problem. So there won't be similar function

**Comment by wouiSB** [comment]
But if you only need the nodes' information without any rules, you can replace the `sub` in the link with `provider`
For example, change `https://example.com/sub?url=your_subscription` into `https://example.com/provider?url=your_subscription`
It can also be found in [docs](https://subconv.is-sb.com/zh_CN/guide/advanced-usage/apis.html)
