### ISSUE TITLE
转换的订阅链接无法使用并报错

### ISSUE THREAD

**Issue by yuhuan05** [SubConv/SubConv#42]
转换vmess节点和转换clash订阅链接均出现该报错，究竟是哪里出了问题，望赐教
![微信截图_20240525060854](https://github.com/SubConv/SubConv/assets/39573969/c91068b5-6701-4899-ad5d-05192950e25a)

**Comment by yuhuan05** [comment]
![微信截图_20240525061543](https://github.com/SubConv/SubConv/assets/39573969/3b0402d4-9b2e-4d44-8d50-99a69a3938e1)
附上14行的报错

**Comment by wouiSB** [comment]
不支持clash for Windows，准确的说是不支持原版clash内核
