### ISSUE TITLE
非严肃建议：内置所有规则到代码库，生成YAML时使用本地的模板

### ISSUE THREAD

**Issue by SunsetMkt** [SubConv/SubConv#47]

**Comment by wouiSB** [comment]
为什么要用本地规则

**Comment by SunsetMkt** [comment]
客户端加载会快一点，Meta Android端会单独显示每个分配置的下载进度。

________________________________

**Comment by SunsetMkt** [comment]
提供/proxy接口这种方法也不是特别安全，可能会被利用。允许用户设置自己的代理URL可能会好一点。对于任何部署在自己的服务器上的人来说，这相当于提供了一个公开的GET代理。

**Comment by SunsetMkt** [comment]
一个缓解方法是，只允许`/proxy`以`https://raw.githubusercontent.com/SubConv/ZJU-Rule/`开头的URL。
